services:
  - type: web
    name: validador-e-emissor-de-ingressos-qr-code
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_URL
        sync: false
