# Exported from Render on 2026-09-04T01:30:42Z
version: "1"
projects:
- name: pablo
  environments:
  - name: Production
    services:
    - type: web
      name: validador-e-emissor-de-ingressos-qr-code
      runtime: node
      repo: https://github.com/aentrosada/validador-e-emissor-de-ingressos-qr-code
      plan: 0.5c-512mb
      envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_CPF
        sync: false
      - key: SHEETS_SYNC_URL
        sync: false
      region: oregon
      buildCommand: bun install && bun run build
      startCommand: bun run start
      autoDeployTrigger: commit
